from tkinter import *
sk=Tk()
sk.geometry("290x540")
sk.maxsize(290,540)
sk.title("Calculater by Saheb kumar")
def click(event):
    global scvalue
    text=event.widget.cget("text")
    print("hello")
    if text == "=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text=="c":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()



scvalue=StringVar()
scvalue.set("")

screen=Entry(sk,textvariable=scvalue,font="lucica 40 bold",bg="light yellow")
screen.pack()
f=Frame(sk,bg="grey",padx=3,pady=3)
b=Button(f,text="9",font="lucica 30 bold",bg="light green")
b.grid(row=0,column=0,padx=5,pady=6)
b.bind("<Button-1>",click)
f.place(x=0,y=67)
b=Button(f,text="8",font="lucica 30 bold",bg="light green")
b.grid(row=0,column=1,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="7",font="lucica 30 bold",bg="light green")
b.grid(row=0,column=2,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="/",font="lucica 30 bold",bg="light green")
b.grid(row=0,column=3,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="6",font="lucica 30 bold",bg="light green")
b.grid(row=1,column=0,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="5",font="lucica 30 bold",bg="light green")
b.grid(row=1,column=1,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="4",font="lucica 30 bold",bg="light green")
b.grid(row=1,column=2,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="*",font="lucica 30 bold",bg="light green")
b.grid(row=1,column=3,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="3",font="lucica 30 bold",bg="light green")
b.grid(row=2,column=0,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="2",font="lucica 30 bold",bg="light green")
b.grid(row=2,column=1,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="1",font="lucica 30 bold",bg="light green")
b.grid(row=2,column=2,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="-",font="lucica 30 bold",bg="light green")
b.grid(row=2,column=3,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="c",font="lucica 30 bold",bg="green")
b.grid(row=3,column=0,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="0",font="lucica 30 bold",bg="light green")
b.grid(row=3,column=1,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text=".",font="lucica 30 bold",bg="light green")
b.grid(row=3,column=2,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="+",font="lucica 30 bold",bg="light green")
b.grid(row=3,column=3,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="%",font="lucica 30 bold",bg="light green")
b.grid(row=4,column=2,padx=2,pady=3)
b.bind("<Button-1>",click)
b=Button(f,text="=",font="lucica 30 bold",bg="red")
b.grid(row=4,column=3,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text="(",font="lucica 30 bold",bg="light green")
b.grid(row=4,column=0,padx=5,pady=6)
b.bind("<Button-1>",click)
b=Button(f,text=")",font="lucica 30 bold",bg="light green")
b.grid(row=4,column=1,padx=5,pady=6)
b.bind("<Button-1>",click)


sk.mainloop()
